package com.heroliu.pojo;

// default package
// Generated Jul 1, 2016 10:13:28 AM by Hibernate Tools 4.0.0

/**
 * Diary generated by hbm2java
 */
public class Diary implements java.io.Serializable {

	private Integer id;
	private String uuid;
	private String title;
	private String article;

	public Diary() {
	}

	public Diary(String uuid, String title, String article) {
		this.uuid = uuid;
		this.title = title;
		this.article = article;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getArticle() {
		return this.article;
	}

	public void setArticle(String article) {
		this.article = article;
	}

}
