package com.heroliu.pojo;

// default package
// Generated Jul 1, 2016 10:13:28 AM by Hibernate Tools 4.0.0

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer uid;
	private String uuid;
	private String uname;
	private String upassword;

	public User() {
	}

	public User(String uuid, String uname) {
		this.uuid = uuid;
		this.uname = uname;
	}

	public User(String uuid, String uname, String upassword) {
		this.uuid = uuid;
		this.uname = uname;
		this.upassword = upassword;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUpassword() {
		return this.upassword;
	}

	public void setUpassword(String upassword) {
		this.upassword = upassword;
	}

}
